- hosts: localhost
  tasks:
  - name: Create Azure RDS Deployment
    azure_rm_deployment:
        state: present
        resource_group_name: Demo-RDSDeployment
        template_link: 'https://raw.githubusercontent.com/metnetwork/MetNet-AzureRDSFarm/master/azuredeploy.json'
        parameters_link: 'https://raw.githubusercontent.com/metnetwork/MetNet-AzureRDSFarm/master/azuredeploydemo.parameters.json'